amcl:
  ros__parameters:
    alpha1: 0.5
    alpha2: 0.2
    alpha3: 0.5
    alpha4: 0.2
    base_frame_id: "base_link"
    global_frame_id: "map"
    laser_model_type: "likelihood_field"
    max_beams: 100
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    tf_broadcast: true
    transform_tolerance: 0.5
    update_min_d: 0.05
    z_hit: 0.85
    z_max: 0.05
    z_rand: 0.05
    z_short: 0.05