amcl:
  ros__parameters:
    alpha1: 0.05
    alpha2: 0.02
    alpha3: 0.025
    alpha4: 0.01
    base_frame_id: "base_link"
    global_frame_id: "map"
    laser_model_type: "likelihood_field"
    max_beams: 100
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    tf_broadcast: true
    transform_tolerance: 0.5
    z_hit: 0.95
    z_rand: 0.05
    # Parameters because our map is small
    update_min_d: 0.2
    laser_likelihood_max_dist: 0.15
    laser_max_range: 5.0
